# Generated by Django 3.2.16 on 2023-01-26 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='Categoria',
            new_name='categoria',
        ),
    ]
